clusters:
  - id: lc-pg-main
    name: lc-pg-main
    patroni_scope: lc-pg-main
    patroni_seed_url: http://127.0.0.1:18080
    poll_interval_sec: 5
    pgbackrest:
      enabled: true
      stanza: lc-pg-main
    docker_hosts:
      "172.18.0.2": logcollector-cihangedik-node0
      "172.18.0.3": logcollector-cihangedik-node1
      "172.18.0.4": logcollector-cihangedik-node2

  - id: lc-pg-vanilla
    name: lc-pg-vanilla
    patroni_scope: lc-pg-vanilla
    patroni_seed_url: http://127.0.0.1:19080
    poll_interval_sec: 5
    pgbackrest:
      enabled: true
      stanza: lc-pg-vanilla
    docker_hosts:
      "172.19.0.2": logcollector-dev-cihangedik-node0
      "172.19.0.3": logcollector-dev-cihangedik-node1
      "172.19.0.4": logcollector-dev-cihangedik-node2

  - id: bc-pg-main
    name: bc-pg-main
    patroni_scope: bc-pg-main
    patroni_seed_url: http://127.0.0.1:20080
    poll_interval_sec: 5
    pgbackrest:
      enabled: true
      stanza: bc-pg-main
    docker_hosts:
      "172.20.0.2": bundlecollect-cihangedik-node0
      "172.20.0.3": bundlecollect-cihangedik-node1
      "172.20.0.4": bundlecollect-cihangedik-node2
